production:
  adapter: postgresql
  encoding: unicode
  database: flindersapi
  pool: 5
  username: flindersapi
  password: password

development:
  adapter: postgresql
  encoding: unicode
  database: flindersapi
  pool: 5
  username: flindersapi
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: flindersapi_test
  pool: 5
  username: flindersapi
  password: password