production:
  adapter: postgresql
  encoding: unicode
  database: unibuddyapi
  pool: 5
  username: unibuddyapi
  password: password

development:
  adapter: postgresql
  encoding: unicode
  database: unibuddyapi
  pool: 2
  username: unibuddyapi
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: unibuddyapi_test
  pool: 5
  username: unibuddyapi
  password: password
