production:
  adapter: postgresql
  encoding: unicode
  database: flindersapi
  pool: 5
  username: flindersapi
  password: password

#development:
#  adapter: postgresql
#  encoding: unicode
#  database: flindersapi
#  pool: 5
#  username: flindersapi
#  password: password

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000



test:
  adapter: postgresql
  encoding: unicode
  database: flindersapi_test
  pool: 5
  username: flindersapi
  password: password